# Generated by Django 5.2.1 on 2025-05-22 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Орналасқан жері')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Туған күні')),
                ('profile_image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/', verbose_name='Профиль суреті')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профильдер',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('event_reminders', models.BooleanField(default=True)),
                ('news_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4285f4', max_length=7)),
                ('secondary_color', models.CharField(default='#34a853', max_length=7)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
