# Generated by Django 5.2.1 on 2025-05-22 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('category', models.CharField(choices=[('motivation', 'Мотивация'), ('advice', 'Кеңес'), ('tech', 'Технология'), ('education', 'Білім')], default='motivation', max_length=20, verbose_name='Санат')),
                ('source', models.URLField(blank=True, verbose_name='Дереккөз')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Сурет')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған уақыт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тақырып')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('date', models.DateField(verbose_name='Күні')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Уақыты')),
                ('priority', models.CharField(choices=[('low', 'Төмен'), ('medium', 'Орташа'), ('high', 'Жоғары')], default='medium', max_length=10, verbose_name='Басымдылық')),
                ('notification_time', models.DateTimeField(blank=True, null=True, verbose_name='Ескерту уақыты')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('color', models.CharField(default='#4285f4', max_length=7, verbose_name='Түсі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Күнтізбе оқиғасы',
                'verbose_name_plural': 'Күнтізбе оқиғалары',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='entries/')),
                ('media_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('idea', 'Идея')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
