# Generated by Django 5.2.1 on 2025-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(verbose_name='Мәтін')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('phrase_type', models.CharField(choices=[('daily', 'Күнделікті'), ('success', 'Жетістік'), ('work', 'Жұмыс'), ('life', 'Өмір')], default='daily', max_length=20, verbose_name='Түрі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
            ],
            options={
                'verbose_name': 'Мотивациялық мәтін',
                'verbose_name_plural': 'Мотивациялық мәтіндер',
            },
        ),
    ]
