# Generated by Django 5.2.1 on 2025-05-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_motivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хабарландыру',
                'verbose_name_plural': 'Хабарландырулар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарияланған')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Жазба',
                'verbose_name_plural': 'Жазбалар',
                'ordering': ['-created_at'],
            },
        ),
    ]
